<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <RootNamespace>TaskItemIndicator.Shared</RootNamespace>
    <AssemblyName>TaskItemIndicator.Shared</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
